In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../output\ptitle_segment_prepruning.csv',index_col=0)
df['k_fold'] = (df.index // 15 + 1).values
df

,segment,recall,precision,f1_score,valid_recall,valid_precision,valid_f1_score,k_fold
0,0,0.393548,0.697143,0.503093,0.162162,0.400000,0.230769,1
1,1,0.668803,0.828042,0.739953,0.558140,0.545455,0.551724,1
2,2,0.454802,0.838542,0.589744,0.375000,0.600000,0.461538,1
3,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
4,4,0.554217,0.741935,0.634483,0.470588,0.727273,0.571429,1
...,...,...,...,...,...,...,...,...
145,10,0.439024,0.638298,0.520231,0.136364,0.375000,0.200000,10
146,11,0.411417,0.687500,0.514778,0.177419,0.275000,0.215686,10
147,12,0.405705,0.695652,0.512513,0.265060,0.415094,0.323529,10
148,13,0.539877,0.678663,0.601367,0.378788,0.454545,0.413223,10
149,14,0.491443,0.679054,0.570213,0.250000,0.379310,0.301370,10

In [ ]:

temp = df.groupby('k_fold').mean().drop('segment', axis=1)
temp

In [3]:
df = pd.read_csv('../output\ptitle_segment_nopruning.csv',index_col=0)
df['k_fold'] = (df.index // 15 + 1).values
df.groupby('k_fold').mean().drop('segment', axis=1)

,recall,precision,f1_score,valid_recall,valid_precision,valid_f1_score
k_fold,,,,,,
1,1.0,1.0,1.0,0.280883,0.265799,0.268330
2,1.0,1.0,1.0,0.323755,0.297096,0.306547
3,1.0,1.0,1.0,0.342327,0.294210,0.309492
4,1.0,1.0,1.0,0.327364,0.321958,0.322463
5,1.0,1.0,1.0,0.366987,0.323290,0.339017
6,1.0,1.0,1.0,0.300180,0.271305,0.280373
7,1.0,1.0,1.0,0.290034,0.258891,0.269579
8,1.0,1.0,1.0,0.307799,0.303024,0.299543
9,1.0,1.0,1.0,0.309159,0.330237,0.312525
10,1.0,1.0,1.0,0.278384,0.289528,0.278228